### PR TITLE
signed comeplete-final-with-encoding

### PR DESCRIPTION
**Pull request by SDesai71**
encoging

### CODE REVIEW

**Comment by SDesai71** [comment]
encoding

**Comment by jim-parry** [comment]
Policies looks good here, but Home looks messed up !?
"signed complete..." is not a helpful PR title

**Comment by SDesai71** [comment]
Can you unmerge everything? Ill do it again. Merging gives me conflicts and since its the same content its hard to remove the old one because I do not know which is which. . You never told us before it has to be UTF-8 encoding and it doesn't say that on the assignment page either.

**Comment by jim-parry** [comment]
Let's deal with this in class on Weds.
UTF-8 is the normal encoding in Linux, tho not necessarily in Windows.
If you look at the page source where your tet shows wonky, you should see the first meta tag specifiying the charset as UTF-8.

**Comment by SDesai71** [comment]
In terms of completing the assignment am i good? I can fix it and submit again if needed.

**Comment by jim-parry** [comment]
Not yet, but we have time to fix it in class - assignment 1 isn't due until the 13th :)

**Pull request closed without merging**
